version: '3.9'

services:
  nginx:
    image: nginx:1.22.0
    restart: on-failure
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/configs/:/etc/nginx/sites-enabled/:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./staticfiles/:/var/www/app/static/
      - ./media/:/var/www/app/media/

  web:
    build:
      context: .
      dockerfile: ./compose/production/Dockerfile
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    restart: on-failure
    command: /start
